### ISSUE TITLE
Responsewriter status in before funcs is broken

### ISSUE THREAD

**Issue by marcosnils** [urfave/negroni#129]
This commit https://github.com/urfave/negroni/commit/8b113cd90ea0a4dcd51cac1c8addb5ebc927532d broke the ability to retrieve the request status code inside a middleware

As you can see, status header is set before actually calling `callBefore` (https://github.com/urfave/negroni/blob/master/response_writer.go#L46-L47) so I was retrieving the status code in my before funcs. 

Now with this new validation  https://github.com/urfave/negroni/blob/master/response_writer.go#L62-L69 it's not possible anymore. 

@jszwedko

**Comment by marcosnils** [comment]
> Now with this new validation https://github.com/urfave/negroni/blob/master/response_writer.go#L62-L69 it's not possible anymore.

I know it's possible but I shouldn't have to change my code as this should work as indicated.

**Comment by marcosnils** [comment]
Fix in https://github.com/urfave/negroni/pull/130

**Comment by jszwedko** [comment]
Closed by #124 -- thanks again for the report!
