### ISSUE TITLE
Pass along request context to downstream middleware/controller

### ISSUE THREAD

**Issue by owenthereal** [urfave/negroni#14]
I really like the idea of a less magical middleware systems. I'm wondering if there's any plan to add capability to pass objects downstream to another middleware/controller, a.k.a. a request context. For example, I've a `Auth` middleware which authenticates users and return a `User` object. Is there a way to pass along this instance to downstream middleware/controller?

**Comment by jeremiahmmartinez** [comment]
Some have stated that sending dependencies in the request context is bad form due to possible runtime errors. Is there any way to send additional arguments to a handler?

**Comment by elithrar** [comment]
Sending per-request data - e.g. something derived from the request itself, like a userID lookup, or JWT claim, or request ID - is totally fine within the context. That's what a request context is for - data that only needs to live as long as the request itself.

Database connection pools, caches, etc - long lived objects - should be passed as function arguments.

**Comment by jszwedko** [comment]
@elithrar's got it.

For per request things, [`pgk/context`](https://golang.org/pkg/context/) or Gorilla's `context` is a good choice, for initializing middleware, the examples in this repo should help.

You are right that you lose runtime type safety for request context values, but I haven't seen an approach that maintains that.
