### ISSUE TITLE
Mention the Debian package in the Getting Started section of README.md

### ISSUE THREAD

**Issue by freeekanayaka** [urfave/negroni#152]
Hello,

this is mainly to notify you upstreams that I packaged negroni for Debian:

https://packages.debian.org/sid/golang-github-urfave-negroni-dev

If you'd like to mention the option of installing via Debian package ("apt install golang-github-urfave-negroni-dev") somewhere in the README.md, that would be nice.

Otherwise feel free to close this issue.

Thanks and take care

**Comment by jszwedko** [comment]
Very cool, I'll add it to the README.
