### ISSUE TITLE
ResponseWriter calls CloseNotifier on http.ResponseWriters that don't implement it

### ISSUE THREAD

**Issue by willfaught** [urfave/negroni#153]
var req = httptest.NewRequest("GET", "/", nil)
    var res = negroni.NewResponseWriter(httptest.NewRecorder())

    [...].ServeHTTP(res, req)

    panic: interface conversion: *httptest.ResponseRecorder is not http.CloseNotifier: missing method CloseNotify [recovered]
    	panic: interface conversion: *httptest.ResponseRecorder is not http.CloseNotifier: missing method CloseNotify

    goroutine 14 [running]:
    panic(0x4d4680, 0xc420011640)
    	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
    testing.tRunner.func1(0xc4201ea900)
    	/usr/local/Cellar/go/1.7.3/libexec/src/testing/testing.go:579 +0x25d
    panic(0x4d4680, 0xc420011640)
    	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:458 +0x243
    github.com/bigcommerce-labs/cp-middleware/vendor/github.com/urfave/negroni.(*responseWriter).CloseNotify(0xc4200115c0, 0x5b3150)
    	/Users/will.faught/Developer/go/src/github.com/bigcommerce-labs/cp-middleware/vendor/github.com/urfave/negroni/response_writer.go:86 +0x5f
    net/http/httputil.(*ReverseProxy).ServeHTTP(0xc420011600, 0xd410b8, 0xc4200115c0, 0xc4201ec870)
    	/usr/local/Cellar/go/1.7.3/libexec/src/net/http/httputil/reverseproxy.go:158 +0xac4

**Comment by jszwedko** [comment]
Hi @willfaught,

Can you provide a more complete example demonstrating your issue? The error you are seeing is accurate, `httptest.ResponseRecorder` is not actually a `http.CloseNotifier`. This may be related to https://github.com/urfave/negroni/pull/151 was merged recently which now bubbles up whether the wrapped `ResponseWriter` actually implements `CloseNotifier` (previously, it would purport to even if it didn't, but than `panic` when you actually called it).

Thank you!

**Comment by jszwedko** [comment]
Actually, look more closely, I think you may have encountered the same issue that @pboyd addressed in #151 -- can you pull latest and try that?

**Comment by willfaught** [comment]
I'm running an old locked version, so I bet this is indeed fixed in head.
Thanks!

**Comment by jszwedko** [comment]
Awesome, I'll close this out, but please feel free to reopen if that doesn't address it!
