### ISSUE TITLE
http.DefaultServeMux + URL-dependent middleware

### ISSUE THREAD

**Issue by bronger** [urfave/negroni#156]
I need an authenticated user (realised by `checkLogin`) for most endpoints but not for `/login` of course.  And, I'd like to use `http.DefaultServeMux` for routing.  This is how I did it:

```go
Mux = negroni.New()
Mux.UseHandler(http.DefaultServeMux)
authenticatedRouter := http.NewServeMux()
http.Handle("/", negroni.New(negroni.HandlerFunc(checkLogin),
	negroni.Wrap(authenticatedRouter)))

http.HandleFunc("/login", login)
authenticatedRouter.HandleFunc("/users/", usersDispatch)
authenticatedRouter.HandleFunc("/matches/", matchesDispatch)
```

Is is a good way to achieve this?  It works for me, at least. This nesting of handlers bothers me … however, it is necessary, isn't it?

**Comment by jszwedko** [comment]
Hi @bronger,

What you have there is essentially correct. One other tact you could take is to have one mux where you initialize the middleware handling the authentication checking have a whitelist of routes to not require authentication for.

**Comment by bronger** [comment]
Thank you very much!  This answers my question.
