### ISSUE TITLE
context values cleared after handler 

### ISSUE THREAD

**Issue by alecha** [urfave/negroni#160]
Hi all, I'm using Negroni together with gorilla mux router (updated to the latest version).

What I'm seeing is that the values in the request's context (using the new builtin context package) are cleared after the handler execution. I've also checked gorilla's documentation and I've updated to the latest version (they're now using the native context if Go 1.7 is used to build the program).

In particular, inside the `voidMiddleware` function, the last call to it doesn't have the context values se (it appears to me that the latest version of gorilla doesn't do anything and don't clear that values)

How can I solve?

Thanks,
Alessio

Example code:
```go
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"

	"github.com/urfave/negroni"
)

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		r = r.WithContext(context.WithValue(r.Context(), "userId", 100))
		log.Printf("___userID in handler: %v", r.Context().Value("userId"))
		fmt.Fprintf(w, "Welcome to the home page!")
	})

	n := negroni.Classic()
	n.Use(negroni.HandlerFunc(MyMiddleware))
	n.UseHandler(mux)

	http.ListenAndServe(":3000", n)
}

func MyMiddleware(rw http.ResponseWriter, r *http.Request, next http.HandlerFunc) {
	next(rw, r)
	log.Printf("___userID after handler: %v", r.Context().Value("userId"))
}
```

**Comment by elvizlai** [comment]
Same issue, I need resp in the end to log. But can not do this.

**Comment by ronorato** [comment]
I am seeing the same problem as well.  Is there a none workaround for this?

**Comment by yanfali** [comment]
You can't inject the context into a endpoint handler, you can only use values from there because you can't pass the wrapped http.Request. You need to create a middleware that runs before 

Try something like this:

```go
func UserInjector(rw http.ResponseWriter, r *http.Request, next http.HandlerFunc) {
	rPrime = r.WithContext(context.WithValue(r.Context(), "userId", 100))
	next(rw, rPrime)
}

n.Use(negroni.HandlerFunc(UserInjector)) // put this before MyMiddleware
```

**Comment by jszwedko** [comment]
As @alecha notes, reassigning `r` in:

```
mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		r = r.WithContext(context.WithValue(r.Context(), "userId", 100))
		log.Printf("___userID in handler: %v", r.Context().Value("userId"))
		fmt.Fprintf(w, "Welcome to the home page!")
	})
```

will only result in the value being available in that handler (it won't modify the passed in `r` outside of the function).

@elvizlai @ronorato does this also help your use cases as well?

**Comment by elvizlai** [comment]
@jszwedko @alecha this does not solve my problem. I need stdout http resp log in middle ware. This can not be done.

**Comment by jszwedko** [comment]
@elvizlai can you please provide some example code that demonstrates your issue? I'm having difficulty understanding.

**Comment by ronorato** [comment]
This does not solve my issue either.  I ended up abandoning the approach and went down a different path.  I could never get the value set by the middleware to show up in the gorilla based route.

**Comment by jszwedko** [comment]
@ronorato interesting, I'm happy to look at some sample code if its helpful; I feel like I might be missing something.

**Comment by ronorato** [comment]
@jszwedko I would be happy to try and recreate the issue I was having.  I will look at trying to get something coded up tomorrow for you to look at.

**Comment by elvizlai** [comment]
@ronorato  an example blew

```
package main

import (
	"context"
	"log"
	"net/http"
	"time"

	"github.com/julienschmidt/httprouter"
	"github.com/pborman/uuid"
	"github.com/urfave/negroni"
)

type ContextResponseWriter struct {
	http.ResponseWriter
	Context context.Context
}

func main() {
	n := negroni.New()
	n.Use(LogMiddleware())
	n.UseHandler(SetRouterV1())

	http.ListenAndServe(":3000", n)
}

type Router struct {
	prefix string
	*httprouter.Router
}

func NewWithPrefix(prefix string) *Router {
	return &Router{prefix: prefix, Router: httprouter.New()}
}

func (r *Router) Register(uri string, handlers ...negroni.HandlerFunc) {
	n := negroni.New()
	for _, h := range handlers {
		n.UseFunc(h)
	}
	r.Handler("POST", r.prefix+uri, n)
}

func Wrap(handler http.HandlerFunc) negroni.HandlerFunc {
	return func(rw http.ResponseWriter, r *http.Request, next http.HandlerFunc) {
		handler(rw, r)
		next(rw, r)
	}
}

func SetRouterV1() *Router {
	v1 := NewWithPrefix("/v1")

	v1.Register("/mock/test", Wrap(MockTest))

	return v1
}

// We can not change the handler func now, the params can only be http.ResponseWriter and *http.Request
func MockTest(rw http.ResponseWriter, r *http.Request) {
	// TODO
	// I need set some resp body to ctx, so that I can print out in the end of LogMiddleware
}
func LogMiddleware() negroni.HandlerFunc {
	return func(rw http.ResponseWriter, r *http.Request, next http.HandlerFunc) {
		start := time.Now()
		tid := uuid.New()
		rw.Header().Set("X-Request-ID", tid)

		version := r.Header.Get("X-App-Version")

		ctx := r.Context()
		ctx = context.WithValue(ctx, "tid", tid)

		next(rw, r.WithContext(ctx))

		// TODO
		// I need get 'body resp' here
		if status := rw.(negroni.ResponseWriter).Status(); status == http.StatusOK {
			log.Printf("tid=%s, from=%s, method=%s, remote=%s, agent=%s, version=%s, req=%s, status=%d, took=%dms", tid, r.RequestURI, r.Method, r.RemoteAddr, r.UserAgent(), version, "body resp", status, time.Since(start).Nanoseconds()/1000000)
		} else {
			log.Printf("tid=%s, from=%s, method=%s, remote=%s, agent=%s, version=%s, req=%s, status=%d, took=%dms", tid, r.RequestURI, r.Method, r.RemoteAddr, r.UserAgent(), version, "body resp", status, time.Since(start).Nanoseconds()/1000000)
		}
	}
}

```

**Comment by jszwedko** [comment]
@elvizlai thank you for the example code!

It looks like you are going to run into the same issue I described in https://github.com/urfave/negroni/issues/160#issuecomment-271185113. You cannot set `net/http/context` values in the handler itself because the only way to modify a request's context is via `WithContext` which returns a new copy of the request with the new context. That `Request` struct will only exist within the scope of the handler. This is a result of the way that `net/http` implements the context pattern.

You can see https://github.com/urfave/negroni/issues/160#issuecomment-270258488 for an example of another route you can take by setting context values in their own middlewares (which are able to propagate the modified context).

Please let me know if this is still unclear.

**Comment by elvizlai** [comment]
@jszwedko thanks for you idea.
 I know what #160(comment) does. But I need change all my handler(rw, r) to handler(rw, r, next), this may be a huge changes for my project. 
May I'd better try to hack negroni.ResponseWriter

**Comment by jszwedko** [comment]
@elvizlai :+1: if you come up with anything, I'd be interested in seeing it.

You could also consider `gorilla/context` (http://www.gorillatoolkit.org/pkg/context) which allows you to associate metadata with a request through an external data structure (rather than on the request itself).

**Comment by jszwedko** [comment]
Closing this out since this isn't an issue with `negroni`, but with the way that `context` wants to be used.
