### ISSUE TITLE
Classic logging is broken

### ISSUE THREAD

**Issue by marcosnils** [urfave/negroni#166]
I haven't looked at the code in depth, but I believe https://github.com/urfave/negroni/commit/2cb24dac5043933255b7079ac36533e331c27b64 introduced a bug that made classic logging stopped working

I remember that the negroni printed the status code, the path, the response time and the timestamp of each request with that logger and now it only prints an incorrectly timestamp. 

This is what I get from running the example in the README

```s
marcos@marcos-xps:~/Projects/gopath/src/github.com/marcosnils/gotest$ go run main.go 
[negroni] 2006-01-02T15:04:05Z07:00
[negroni] 2006-01-02T15:04:05Z07:00
[negroni] 2006-01-02T15:04:05Z07:00
[negroni] 2006-01-02T15:04:05Z07:00
[negroni] 2006-01-02T15:04:05Z07:00
[negroni] 2006-01-02T15:04:05Z07:00
[negroni] 2006-01-02T15:04:05Z07:00
```

**Comment by jszwedko** [comment]
Should be fixed by #164; apologies that that one slipped through. I'm in the process of adding a test to catch it in the future.
