### ISSUE TITLE
ResponseWriter.Status does not behave as described

### ISSUE THREAD

**Issue by nmiyake** [urfave/negroni#180]
Currently, the documentation on `ResponseWriter.Status()` states:

```
// Status returns the status code of the response or 200 if the response has
// not been written (as this is the default response code in net/http)
```

https://github.com/urfave/negroni/blob/master/response_writer.go#L16

However, this is not reflected by the implementation, which returns the status directly (which is 0 when a write has not occurred): https://github.com/urfave/negroni/blob/master/response_writer.go#L67

This behavior is also enforced/verified by a unit test: https://github.com/urfave/negroni/blob/master/response_writer_test.go#L53

Either the documentation on `ResponseWriter.Status()` should be updated to remove the reference to returning 200 if the status has not been written or the implementation should be updated to provide this behavior.

**Comment by jszwedko** [comment]
Doh, yep, neglected to update the comment as part of #127 -- thanks for catching this @nmiyake !
