### ISSUE TITLE
Feature Request: Logging POST fields

### ISSUE THREAD

**Issue by petrovicboban** [urfave/negroni#188]
Hi,  
currently, LogEntry struct is:  
```
type LoggerEntry struct {
	StartTime string
	Status    int
	Duration  time.Duration
	Hostname  string
	Method    string
	Path      string
}
```
so, I expect that there is no way to set logging so POST fields are logged.  
Can you add it?

**Comment by jszwedko** [comment]
Hi @petrovicboban,

Logging `POST` fields would require decoding the body of the request. As this would rather drastically increase resource utilization I hesitate to make it part of the default behavior of `negroni.Logger`. Logging the request body is also not a use case I've come across very often, but I am interested if there is a strong enough need to include it in `negroni` itself.

In the meanwhile, I would recommend creating your own logging middleware (perhaps using `negroni.Logger` as a template), but additionally log the request body.

Let me know what you think!

**Comment by petrovicboban** [comment]
Hi @jszwedko ,
We need it because the most of our request are POSTs and they all go to single url. Parameters are different, so logging only url are pointless for us.  
Anyway, I created new logging middleware, which is almost the same as default one (just couple of lines modified and added), and it works.  
  
The question: I was using `n := negroni.Classic()` in main code. Should I replace it with:  
```
	n := negroni.New()
 	n.Use(negroni.NewRecovery())
 	n.Use(utilities.NewLogger())   
```
New Logger middleware is in utilities package. We don't use static middleware.

**Comment by jszwedko** [comment]
Yep!

You can make it a bit more concise with:

```
n := negroni.New(negroni.NewRecovery(), utilities.NewLogger())
```

Glad to hear you were able to implement your logger.
