### ISSUE TITLE
panics crashing negroni

### ISSUE THREAD

**Issue by pjebs** [urfave/negroni#190]
I noticed that the Recovery middleware only protects the Application if the panic occurs inside the endpoint handler and and functions directly called inside the endpoint handler all the way down the chain etc.

If the panic happens inside a goroutine inside the endhander, negroni can't assist us. This could be due to a third party library we are using.

eg.

```
func Handler(w http.ResponseWriter, r *http.Request) {
   panic("XXX") //Negroni protects app from crashing via the Recovery middleware.
}

```

This will cause negroni to crash:
```
func Handler(w http.ResponseWriter, r *http.Request) {
   go func( ) {
      panic("ZZZ") //Negroni does not protect us. Application crashes.
   }()
}

```
Obviously this is a contrived example but it could happen because a third party library that we have no control over does this.

**Comment by pjebs** [comment]
Is there anyway to protect against rogue goroutines?

**Comment by jszwedko** [comment]
Hi @pjebs,

`panic`s in a goroutine only bubble up to the top level function (the one executed by `go X`) so the recovery handler will not be able to catch these (see: https://golang.org/ref/spec#Handling_panics).

**Comment by pjebs** [comment]
Maybe this should be a feature request for Go.10 because it's quite dangerous for a use case like a web-server.

**Comment by jszwedko** [comment]
Agreed, it would be nice to register a handler in cases where you don't have direct control over 3rd party code. I'll close this out for now, but thanks for raising this discussion!
