### ISSUE TITLE
New semver release

### ISSUE THREAD

**Issue by evillemez** [urfave/negroni#201]
Any chance of a new semver release?  I don't mind using master, but working with the new dep tool, it's nice to be able to specify a version in my `Gopkg.toml`, and `0.2.0` is fairly old at this point.

**Comment by sanae10001** [comment]
Me too...
```
dep ensure -add github.com/urfave/negroni@master
```

**Comment by diligiant** [comment]
@urfave please. @sanae10001 being on the master is not really a possibility when you ship production code. There needs to be an assessment that the code is stable therefore the release.

**Comment by jszwedko** [comment]
👍 thanks for the prompt all; I just released 0.3.0.

Let me know if you see any issues!

**Comment by diligiant** [comment]
@jszwedko thank you.
