### ISSUE TITLE
Run() for TLS istances

### ISSUE THREAD

**Issue by Nhoya** [urfave/negroni#205]
What about expand the `Run` function to TLS instances? i know i can just use `http.ListenAndServeTLS`
but integrating it in negroni should be nice

**Comment by jszwedko** [comment]
Hi @Nhoya,

This was discussed in #85 and #106, but we opted to just document better how to use `negroni` with `http.Listen*` functions. the `Run` method is primarily just provided as a convenience wrapper for testing out `negroni`.

Open to new thoughts though!

**Comment by Nhoya** [comment]
Hi @jszwedko and thanks for your reply,
i missed the PR but i still want to point out that at the end of the day people will just use the same function as `Run` but with `ListenAndServeTLS` instead of `ListenAndServe` so integrating in negroni should just be a way to avoid to create a function. I saw in a PR that someone just wanted to have a `Run` function that will be globally comprensive for `ListenAndServe` and `ListenAndServeTLS` what about that? Maybe add a new parameter to it?

**Comment by jszwedko** [comment]
We could do that, but I'd prefer to just have a separate method if we include this convenience wrapper. To clarify, adding this method wouldn't save any lines of code over just using `http.ListenAndServeTLS`:

```go
n := negroni.New()
// ....
n.RunTLS(":3000", certFile, keyFile) //added method
```

vs.

```go
n := negroni.New()
// ....
http.ListenAndServeTLS(":3000", certFile, keyFile, n)
```

The README generally discourages the use of `Run`. I'd like to remove it altogether, but this would, of course, be backwards incompatible. For that reason, I hesitate to add `RunTLS`.

**Comment by Nhoya** [comment]
Well but RunTLS also print info on the port where the server is running, thing that usually everyone will do, so is already a 2x1 line

**Comment by jszwedko** [comment]
Maybe, but one additional line doesn't seem worth it to me to add the helper method. Admittedly, again, I'm coming from the perspective that the `Run` method shouldn't even exist.

**Comment by jszwedko** [comment]
Closing this given it is relatively stale and I still believe that

```go
n := negroni.New()
// ....
http.ListenAndServeTLS(":3000", certFile, keyFile, n)
```

is preferable to a `Run` method for TLS.
