### ISSUE TITLE
Commit variable to middleware

### ISSUE THREAD

**Issue by Fruchtgummi** [urfave/negroni#210]
How i send a variable on middleware-function?

```
router.Handle("/1.0/test/user/{key}",
		negroni.New(
			negroni.HandlerFunc(authentication.RequireTokenAuthentication),
			negroni.HandlerFunc(authentication.StatusGroupAuthentication),
			negroni.HandlerFunc(controllers.GetUserByKey),
		)).Methods("GET")
```

The function have `(rw http.ResponseWriter, req *http.Request, next http.HandlerFunc)`

**Comment by jszwedko** [comment]
Hi @Fruchtgummi, what router are you using?

**Comment by Fruchtgummi** [comment]
gorilla/mux

**Comment by jszwedko** [comment]
@Fruchtgummi you would use `mux` to retrieve the `key` value then (assuming that is the variable you are talking about). Something like:

```
vars := mux.Vars(request)
key := vars["key"]
```

**Comment by Fruchtgummi** [comment]
A you unterstand me or I express myself wrong...

my middleware-fuction `negroni.HandlerFunc(authentication.RequireTokenAuthentication)` 

i would like to `negroni.HandlerFunc(authentication.RequireTokenAuthentication(mywhateveter))`

**Comment by jszwedko** [comment]
Ah, I see, that would work if you have `authentication.RequireTokenAuthentication` return a handler itself. E.g.:

```go
func RequireTokenAuthentication(mywhatever int) negroni.HandlerFunc {
  return func(rw http.ResponseWriter, req *http.Request, next http.HandlerFunc) {
    // access to mywhatever will be available here
  }
}
```

**Comment by Fruchtgummi** [comment]
Thx, good job... :)
