### ISSUE TITLE
more example on PanicHandlerFunc ？

### ISSUE THREAD

**Issue by dfang** [urfave/negroni#221]
how to write to response in PanicHandlerFunc, is there any examples on recovery middleware ?

**Comment by jszwedko** [comment]
Hi @dfang,

You can provide the `Recovery` middleware with a `PanicFormatter` to determine how the response is written.

You can see the [test](https://github.com/urfave/negroni/blob/master/recovery_test.go#L103-L134) for an example of this.

Hope this helps!

**Comment by dfang** [comment]
@jszwedko oh i see, you mean write a formatter implements PanicFormatter (eg. JsonFormatter) ...

thanks !

**Comment by dfang** [comment]
@jszwedko what i want is recover the err, and write the err msg to response,  i can't recover in PanicFormatter, and there is no ResponseWriter in PanicHandler .....

```
![image](https://user-images.githubusercontent.com/1277047/39473836-72984f7c-4d83-11e8-8178-da7baf1a1249.png)

```
custom middleware is better for my situation
