### ISSUE TITLE
Paths containing percent (%) character not being logged correctly

### ISSUE THREAD

**Issue by tohjustin** [urfave/negroni#222]
### Steps to Reproduce
1. Include [negroni](https://github.com/urfave/negroni)'s logger (default logging format) middleware into server
```
func main() {
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	router := mux.NewRouter()
	router.HandleFunc(`/`, handler).Methods("GET")

	n := negroni.New()
	n.Use(negroni.NewRecovery())
	n.Use(negroni.NewLogger())
	n.UseHandler(router)

	http.ListenAndServe(":8080", n)
}
```

2. Send request to server at port `8080` to test logging
```
curl localhost:8080/hello-100%25-blue.svg
```

3. Actual Output - `%` character not logged correctly
```
[negroni] 2018-05-31T00:00:01-07:00 | 200 | 	 1.95076ms | localhost:8080 | GET /hello-100%!b(MISSING)lue.svg
```

4. Expected Output
```
[negroni] 2018-05-31T00:00:01-07:00 | 200 | 	 1.95076ms | localhost:8080 | GET /hello-100%-blue.svg
```

### Proposed Solution
- [logger.go](https://github.com/urfave/negroni/blob/master/logger.go#L75): Convert `URL.path` into a percent encoded string before passing `LoggerEntry` struct into Go template for execution

**Comment by jszwedko** [comment]
Fixed by #223 

Thanks again!
