### ISSUE TITLE
negroni not working with google appengine

### ISSUE THREAD

**Issue by ripplejb** [urfave/negroni#227]
Hi, 

Here is my code.

```
import (
	"fmt"
	. "github.com/gorilla/mux"
	"github.com/urfave/negroni"
	"google.golang.org/appengine"
	"net/http"
)


func main() {
	ng := negroni.New()
	mux := NewRouter()
	mux.HandleFunc("/", func(writer http.ResponseWriter, request *http.Request) {
		fmt.Fprintln(writer, "Hello World !!!")
	}).Methods("GET")
	ng.UseHandler(mux)

	appengine.Main()
}
```
```
INFO     2018-09-09 04:26:28,660 instance.py:294] Instance PID: 24619
INFO     2018-09-09 04:26:32,247 module.py:880] default: "GET / HTTP/1.1" 404 19
INFO     2018-09-09 04:26:32,536 module.py:880] default: "GET /favicon.ico HTTP/1.1" 404 19
```
Am I missing something or is it an issue ?

**Comment by jszwedko** [comment]
Hi @ripplejb,

I don't have personal experience with Google's AppEngine, but looking at google.golang.org/appengine, it appears to be using the default `http.DefaultServeMux` to set up the listener (via `http.ListenAndServe`).

If that is the case, I believe you'll want to add add something like:

```golang
http.Handle("/", ng)
```

to register `ng` is the default handler (before calling `appengine.Main`.

Let me know if this helps!

**Comment by ripplejb** [comment]
This worked. Thank you @jszwedko
