### ISSUE TITLE
PANIC: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by CarterScadden** [urfave/negroni#251]
I have a server that serves a dist/ folder on a GET '/' request. But Negroni panics on any and all POST, PUT, PATCH, or DELETE requests. 

I know this might not be negronis fault, But running this on a docker instance on my local machine works like a charm, while running on a server will return this

`PANIC: runtime error: invalid memory address or nil pointer dereference
goroutine 338 [running]:
github.com/codegangsta/negroni.(*Recovery).ServeHTTP.func1(0x7fb434153028, 0xc00031ef00, 0xc0001100a0)
	/home/user/go/src/github.com/codegangsta/negroni/recovery.go:34 +0xe8
panic(0x6de540, 0x99fc40)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/direcotry/directory2/models.(*Pdb).Message(0x9aa960, 0xc0002b3a40, 0x8, 0x2, 0x2, 0x11, 0x0, 0x0, 0xc000099648)
	/home/user/go/src/github.com/direcotry/directory2/models/models.go:53 +0xa4
github.com/dvlcdr/directory2/models.Message(0xc0002b3a40, 0x8, 0x3, 0x73804e, 0x1, 0x738284, 0x4, 0xc0002b3a40)
	/home/user/go/src/github.com/direcotry/directory2/models/models.go:84 +0xd0
github.com/direcotry/directory2/controllers.FetchAllDb(0x7fb434153028, 0xc00031ef00, 0xc000364d00, 0x0, 0x0, 0x0)
	/home/user/go/src/github.com/direcotry/directory2/controllers/controllers.go:122 +0xef
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000122000, 0x7fb434153028, 0xc00031ef00, 0xc000364d00)
	/home/user/go/src/github.com/julienschmidt/httprouter/router.go:299 +0x6e0
github.com/codegangsta/negroni.Wrap.func1(0x7fb434153028, 0xc00031ef00, 0xc000364d00, 0xc000319840)
	/home/user/go/src/github.com/codegangsta/negroni/negroni.go:41 +0x4d
github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc0001101e0, 0x7fb434153028, 0xc00031ef00, 0xc000364d00, 0xc000319840)
	/home/user/go/src/github.com/codegangsta/negroni/negroni.go:24 +0x4e
github.com/codegangsta/negroni.middleware.ServeHTTP(0x79f180, 0xc0001101e0, 0xc000110280, 0x7fb434153028, 0xc00031ef00, 0xc000364d00)
	/home/user/go/src/github.com/codegangsta/negroni/negroni.go:33 +0x9c
github.com/rs/cors.(*Cors).ServeHTTP(0xc000126000, 0x7fb434153028, 0xc00031ef00, 0xc000364d00, 0xc000319820)
	/home/user/go/src/github.com/rs/cors/cors.go:252 +0x190
github.com/codegangsta/negroni.middleware.ServeHTTP(0x79e780, 0xc000126000, 0xc000110260, 0x7fb434153028, 0xc00031ef00, 0xc000364d00)
	/home/user/go/src/github.com/codegangsta/negroni/negroni.go:33 +0x9c
github.com/codegangsta/negroni.(*Static).ServeHTTP(0xc00011c090, 0x7fb434153028, 0xc00031ef00, 0xc000364d00, 0xc000319800)
	/home/user/go/src/github.com/codegangsta/negroni/static.go:30 +0x78d
github.com/codegangsta/negroni.middleware.ServeHTTP(0x79e740, 0xc00011c090, 0xc000110240, 0x7fb434153028, 0xc00031ef00, 0xc000364d00)
	/home/user/go/src/github.com/codegangsta/negroni/negroni.go:33 +0x9c
github.com/codegangsta/negroni.(*Logger).ServeHTTP(0xc000112098, 0x7fb434153028, 0xc00031ef00, 0xc000364d00, 0xc0003197e0)
	/home/user/go/src/github.com/codegangsta/negroni/logger.go:27 +0x15c
github.com/codegangsta/negroni.middleware.ServeHTTP(0x79e6e0, 0xc000112098, 0xc000110220, 0x7fb434153028, 0xc00031ef00, 0xc000364d00)
	/home/user/go/src/github.com/codegangsta/negroni/negroni.go:33 +0x9c
github.com/codegangsta/negroni.(*Recovery).ServeHTTP(0xc0001100a0, 0x7fb434153028, 0xc00031ef00, 0xc000364d00, 0xc0003197c0)
	/home/user/go/src/github.com/codegangsta/negroni/recovery.go:45 +0x82
github.com/codegangsta/negroni.middleware.ServeHTTP(0x79e720, 0xc0001100a0, 0xc000110200, 0x7fb434153028, 0xc00031ef00, 0xc000364d00)
	/home/user/go/src/github.com/codegangsta/negroni/negroni.go:33 +0x9c
github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc00011c0f0, 0x7a43a0, 0xc00035ca80, 0xc000364d00)
	/home/user/go/src/github.com/codegangsta/negroni/negroni.go:73 +0xdd
net/http.serverHandler.ServeHTTP(0xc0001240d0, 0x7a43a0, 0xc00035ca80, 0xc000364d00)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0002a9220, 0x7a4a60, 0xc0001ce100)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4`

Is there any chance this could be happening from a lack of memory? Or could anyone point me in a good direction to figuring out the problem?

**Comment by jszwedko** [comment]
Hi @CarterScadden 

It looks like the there is a null pointer being dereferenced at `github.com/direcotry/directory2/models.(*Pdb).Message(0x9aa960, 0xc0002b3a40, 0x8, 0x2, 0x2, 0x11, 0x0, 0x0, 0xc000099648) /home/user/go/src/github.com/direcotry/directory2/models/models.go:53 +0xa4`. I might suggest tracing the code from there and identifying how it might get into that state.

This doesn't appear to be related to negroni, but let me know if you find otherwise.

**Comment by jszwedko** [comment]
Closing since this seems unrelated to negroni.
