### ISSUE TITLE
Recovery middleware not setting stack in PanicInformation

### ISSUE THREAD

**Issue by angfl97** [urfave/negroni#252]
on this [line](https://github.com/urfave/negroni/blob/master/recovery.go#L170) 
When using recovery middleware, stack trace will not be set on the infos PanicInformation unless PrintStack is set to true (which is likely undesired). Therefore when using PanicHandlerFunc, one is unable to access the stack trace of the recovered panic, it will just be empty.

**Comment by jszwedko** [comment]
Thanks for the report! I fixed this in #254

**Comment by angfl97** [comment]
Awesome, thanks!
