### ISSUE TITLE
The master branch is not 1.0.0

### ISSUE THREAD

**Issue by rayjlinden** [urfave/negroni#253]
Man - I was looking at how the recovery middleware worked because it was crashing in my app.
(In fact, bug report - you should check that Formatter is not nil before calling.)

But what really had me confused is that master is NOT the latest code.  When you pull things with go modules you will get the 1.0 tag which is a different version.  Why doesn't the version at HEAD of master have a tag?

**Comment by jszwedko** [comment]
Thanks for the bump @rayjlinden . I've tagged the current HEAD of master as `2.0.1`. You can see the changes here: https://github.com/urfave/negroni/blob/master/CHANGELOG.md

I also pushed https://github.com/urfave/negroni/commit/2810f45cff0c5e6dcb35d36abc46ed25c70b3091 to check that the formatter is not nil before calling; thanks for the report!
