### ISSUE TITLE
Negroni and new relic

### ISSUE THREAD

**Issue by rayjlinden** [urfave/negroni#257]
Newrelic provides integrations with several go routers.  Alas Negroni is not one.  So I'm trying create one.

However, one thing they do is wrap the ResponseWriter in the middleware.  I attempted that in Negroni just like it done in several of their other integrations.  However, Negroni does not like that at all and blows up!

I don't suppose there is a way for Negroni to not wrap response writer?  I'm at a loss as to what I should do.  Any ideas?

**Comment by jszwedko** [comment]
Hi @rayjlinden can you provide some more details or example code demonstrating the issue? There is a `negroni.ResonseWriter` struct that you can use to wrap the middleware: https://github.com/urfave/negroni/blob/master/response_writer.go#L31

**Comment by jszwedko** [comment]
Closing due to lack of response.
