### ISSUE TITLE
negroni.ResponseWriter implements http.Flusher even if underlying http.ResponseWriter doesn't

### ISSUE THREAD

**Issue by DenisKuplyakov** [urfave/negroni#265]
negroni.ResponseWriter wrapper of http.ResponseWriter always implements all of http ResponseWriter extensions like http.Flusher, http.Hijacker and etc. But implementation is really dummy inside and doesn't provide guarantees given by these interfaces. For example Flush() method just checks underlying ResponseWriter and calls it's Flush() method.

That may cause problems with the code, that rely it's logic based on the support of such interfaces, like:

```go
func (w http.ResponseWriter) {
    if wf, ok := w.(http.Flusher); ok {
        wf.Flush()
        log.Info("We have flushed successfully")
    }
}
```

The code above thinks that it has flushed something, but really it did not in a case when w is negroni.ResponseWriter.

The same task of wrapping http.ResponseWriter to save info (status, response size and etc.) is solved in promhttp package of client_golang. Their [tricky implementation](https://github.com/prometheus/client_golang/blob/main/prometheus/promhttp/delegator.go) lacks the problem mentioned above.

Sorry, that I don't have links to some real and not toy code, that relies on `wf, ok := w.(http.Flusher); ok` kind of check. But I'm pretty sure that someone may be affected by the problem.

**Comment by jszwedko** [comment]
Hi @DenisKuplyakov !

That is a good observation. It looks like `prometheus/client_golang`'s approach would be workable. I'd happily see a PR for adding that here.

**Comment by jizhuozhi** [comment]
Hello, @jszwedko , I opened a PR #267 try to fix this issue, PLAT
