### ISSUE TITLE
Release the latest tag

### ISSUE THREAD

**Issue by sahilpatil2997** [urfave/negroni#274]
Hey,

Can you please release the latest tag version of negroni?
I would like to know why the latest tag was not released.

**Comment by pbgc** [comment]
@sahilpatil2997 you know you can/should use it with:

```
import (
	"github.com/urfave/negroni/v3"
)
```

right ?

**Comment by sahilpatil2997** [comment]
> @sahilpatil2997 you know you can/should use it with:
> 
> ```
> import (
> 	"github.com/urfave/negroni/v3"
> )
> ```
> 
> right ?

Yes, but the release version is much convenient to manage since the dependabot won't pick the latest version which is not released, so if possible can you please release the latest tagged version which will be manageable in the application?

**Comment by pbgc** [comment]
@sahilpatil2997 I'm not a committer .. I just gave you that info in case you didn't know. Maybe ask @jszwedko

**Comment by jszwedko** [comment]
I'm waiting on review over here: https://github.com/urfave/negroni/pull/276

**Comment by pbgc** [comment]
@jszwedko I think that what @sahilpatil2997 means is that neither V2 or V3 had a release: https://github.com/urfave/negroni/releases

**Comment by jszwedko** [comment]
Aha, I see. I was planning to tag 3.1.0. I didn't realize v2 nor v3 wasn't tagged.

**Comment by pbgc** [comment]
@jszwedko sorry for asking here .. but is this project zombie ? your pull request is waiting for 2 months for a review...

**Comment by dearchap** [comment]
@pbgc The dev in charge of this repo had a baby recently and so cannot make time. I will ping them and see if they can get it approved. Sorry for the wait.

**Comment by pbgc** [comment]
@dearchap thanks for the update! That's a very good motive! I was only afraid that the project would be dead. no prob to wait a little more. family first! thanks again!

**Comment by mariash** [comment]
Hi! Any updates on this? Last version 3.0.0 came out in September 2022. It would be nice to get [this change](https://github.com/urfave/negroni/commit/59d32aab419da1606c459c848c7586ef52b07a4b) to be able to use latest full duplex mode.

**Comment by jszwedko** [comment]
Thanks for the bump @mariash . I merged the changelog update without review and tagged as v3.10 given the delay. I think this project could probably benefit from an additional maintainer or two to keep things chugging along. Please ping me via jesse@szwedko.me if you are interested.

**Comment by pbgc** [comment]
@jszwedko thanks for the merge! Could you tag the release and make a release ? V2 and V3 were not tagged and like it was said above "dependabot won't pick the latest version which is not released"

**Comment by jszwedko** [comment]
@pbgc I did tag the latest release as `v3.1.0`. Are you still having troubles?

**Comment by jszwedko** [comment]
See https://github.com/urfave/negroni/releases/tag/v3.1.0

**Comment by pbgc** [comment]
@jszwedko you are right... sorry!

**Comment by mattcobb** [comment]
Is this because there is a 3.1.0 tag, but it is not released? 
go get github.com/urfave/negroni@v3.1.0
go: github.com/urfave/negroni@v3.1.0: invalid version: go.mod has post-v3 module path "github.com/urfave/negroni/v3" at revision v3.1.0

https://github.com/urfave/negroni/releases  Shows the latest is 1.0.0, but there is a 3.1.0 tag

**Comment by jszwedko** [comment]
@mattcobb you'll want: `go get github.com/urfave/negroni/v3@v3.1.0`.
