### ISSUE TITLE
Feature request: Grouping routes

### ISSUE THREAD

**Issue by alehano** [urfave/negroni#37]
I like Negroni, but I really need grouping routes, like in https://github.com/gin-gonic/gin
Where I can assign specific middlewares to specific groups. It's very useful for authorization section.

**Comment by dimroc** [comment]
@alehano +1.

Also unable to get grouping to work with the documentation here: https://github.com/codegangsta/negroni/blob/master/README.md#route-specific-middleware.

I get 404 not found.

**Comment by dimroc** [comment]
gorilla/mux now has PathPrefix(...).Subrouter which might have been recently added that supports grouping:

```go
	router := mux.NewRouter()
	apiRoutes := router.PathPrefix("/api/v1").Subrouter()
	apiRoutes.HandleFunc("/settings", SettingsHandler).Methods("GET")

	n := negroni.Classic()
	n.Use(SettingsMiddleware(settings))
	n.Use(gzip.Gzip(gzip.DefaultCompression))
	n.UseHandler(context.ClearHandler(router))
	n.Run(":8080")
```

This might be the recommended approach to grouping with gorilla/mux.
