### ISSUE TITLE
Add support for Google context

### ISSUE THREAD

**Issue by pjebs** [urfave/negroni#90]
Are you thinking of updating negroni (I.e. v2) to utilize Google context.

That seems to be idiomatic now. Everyone seems to using it. Or should I attempt to create a fork?

http://godoc.org/golang.org/x/net/context

https://blog.golang.org/context

**Comment by ericwq** [comment]
it seems there is already exist one. gorilla context.

**Comment by pjebs** [comment]
that's a global context. Doesn't scale as well.

**Comment by jszwedko** [comment]
Are you talking about passing a context through the middlewares? I like that negroni currently works with `http.HandlerFunc` so I wouldn't want to see the signature modified -- how were you thinking that it would be implemented @pjebs?

**Comment by zvbuhl** [comment]
Well, negroni works with http.HandlerFunc & http.Handler by wrapping them

How about this?

    type Handler interface {
    	ServeHTTP(ctx context.Context, rw http.ResponseWriter, r *http.Request, next http.HandlerFunc)
    }

Just as now, Wrap calls an http.Handler and then calls next itself, it could receive (and ignore) ctx, call http.Handler and the call next itself.

Then:

    func (n *Negroni) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
    	ctx := context.Background()
    	n.middleware.ServeHTTP(ctx, NewResponseWriter(rw), r)
    }

And so forth.

**Comment by zvbuhl** [comment]
(as an aside, I agree with @pjebs: Google contexts seem to be the most idiomatic way to do this now. They work, they work under load, they work while avoiding global state, and they work well.

**Comment by pjebs** [comment]
https://github.com/guregu/kami

**Comment by mikegleasonjr** [comment]
I forked negroni and httprouter to pass down a Google Context, check my repo. All up to date and tests passing. I haven't updated the readme though.

**Comment by mikegleasonjr** [comment]
Just to follow up on my previous comment, I created a standard for myself for HTTP handlers including a Google Context. Then I forked negroni and httprouter to follow my "standard". If anyone is interested how they work together I can post some code. In the meantime here's my proposed new standard (to stop this nonsense of absolutely trying to be HTTP Handler compliant when it's trivial to write wrappers to switch from one type of Handler to another) Anyway here are the standard my forks are following: https://github.com/mikegleasonjr/go/blob/master/net/http/ctx/ctx.go

**Comment by pbgc** [comment]
Don't see the need to fork negroni to use Google context.
I use it all the time with just a little glue code: https://bitbucket.org/pbgc/nctx/overview

**Comment by zvbuhl** [comment]
I'm currently doing the same with my own glue code, but it'd be nice if negroni supported this natively.

**Comment by pjebs** [comment]
It looks like Google Context will be officially part of standard package starting Go1.7: https://tip.golang.org/doc/go1.7#context

**Comment by jszwedko** [comment]
Indeed it is, but appears that it will be directly accessible on the `Request` struct: https://tip.golang.org/pkg/net/http/#Request.Context so I don't think there will need to be any changes to `negroni`'s API to take advantage of it.

**Comment by pjebs** [comment]
I  wonder if gorilla mux will load url routing values into the context rather than using their own `Vars` function to extract the route variables.

**Comment by rabeesh** [comment]
One solution for it, wrap around `ResponseWriter`.

```
type ContextResponseWriter struct {
	http.ResponseWriter
	Context context.Context
}


// conext value
type Context struct {}

func (Context)  ServeHTTP(w http.ResponseWriter, r *http.Request, n http.HandlerFunc) {
	ctx := context.WithValue(context.Background(), "domain", "universal.webshop")
	ctx = context.WithValue(ctx, "version", "v1")
	ctxrw := &ContextResponseWriter{w, ctx}
	n(ctxrw, r)
}
```

This is not good solution, and you read it like

```
ctx := w.(*app.ContextResponseWriter).Context
version, _ := ctx.Value("version").(string)

fmt.Println("version:", version)
```

**Comment by yanfali** [comment]
I ripped out gorilla/context recently and now use Context to pass around parameters taken from the router library I use (httprouter). It's very easy in middleware/adapters to stuff values in the request context and then pull them back out again in a handler or middleware.

**Comment by catc** [comment]
@yanfali do you happen to have a gist of this? i'm trying to accomplish the same thing

**Comment by yanfali** [comment]
@catc this only works in go1.7, so if you are stuck on an earlier version of go, this won't help.
`net/http` now has a WithContext method.

Basically you're middleware uses the following pattern:

```go
func ServeHTTP(w http.ResponseWriter, r *http.Request, next http.HandlerFunc) {
    ctxt := context.Background()

   // ...middleware does stuff here...

    ctxt = context.WithValue(ctxt, "key", "some new value I want downstream")

    if next != nil {
        next(w, r.WithContext(ctxt))
    }
}
```

Downstream of the middleware, like in a handler or other middleware, you can use `.Context()` to pull values out.

**Comment by yanfali** [comment]
@catc specifically you can use this pattern to stuff the Param value from httprouter into request context and then extract parameters from the router downstream in handlers or other middleware.

**Comment by catc** [comment]
@yanfali I am using 1.7, so that worked perfectly. Thanks!

**Comment by HeyImAlex** [comment]
@yanfali I think that when creating the new context you're supposed to extend from the one already on the request. Because the parent of your replacement context is `context.Background`, it won't actually be closed when the top-level ServeHTTP returns (which is supposed to happen).

```diff
func ServeHTTP(w http.ResponseWriter, r *http.Request, next http.HandlerFunc) {
-    ctx := context.Background()
+    ctx := r.Context()

   // ...middleware does stuff here...

    ctx = context.WithValue(ctx, "key", "some new value I want downstream")

    if next != nil {
        next(w, r.WithContext(ctx))
    }
}
```

**Comment by yanfali** [comment]
Agreed. Sorry if the example was misleading

**Comment by yanfali** [comment]
I think @jszwedko you could probably close this issue as it's not really an issue as of go1.7
